name: Repository Dispatch Workflow

on:
  repository_dispatch:

permissions: write-all

jobs:
  create_file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Access payload, decode and create the playbook file
      run: |
        echo "${{ github.event.client_payload.message.playbook }}" | base64 -d > ${{ github.event.client_payload.message.code }}.yaml

    - name: Commit and push the file
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add *
        git commit -m "Add ${{ github.event.client_payload.message.code }}.yaml file"
        git push
