name: Repository Dispatch Workflow

on:
  repository_dispatch:

jobs:
  create_file:
    runs-on: ubuntu-latest

    steps:

    - name: Access payload and create a file named "test.yaml"
      run: |
        echo "${{ github.event.client_payload.message }}" | base64 -d > test.yaml

    - name: Commit and push the file
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add test
        git commit -m "Add test.yaml file"
        git push
